-- ⚠️ CRITICAL: NO FAKE DATA ⚠️
-- This project uses ONLY real, verified data sources. NO placeholders, NO synthetic data, NO fake values.
-- All data must come from authenticated APIs, official sources, or validated historical records.
--

-- ============================================
-- ADD 110 HIGH-IMPACT FEATURES FOR V3
-- Tier 1 ETFs + Tier 2 Ag Stocks + Tier 3 Energy + Tier 4 Dollar
-- ============================================

-- TIER 1: Ultra-high correlation ETFs (0.82-0.92)
-- SOYB ETF (10 features)
ALTER TABLE `cbi-v14.training.zl_training_prod_allhistory_1m`
ADD COLUMN IF NOT EXISTS soyb_close FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_ma_7d FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_ma_200d FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_bb_upper FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_bb_width FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_atr_14 FLOAT64,
ADD COLUMN IF NOT EXISTS soyb_momentum_10 FLOAT64,

-- CORN ETF (10 features)
ADD COLUMN IF NOT EXISTS corn_etf_close FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_ma_7d FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_ma_200d FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_bb_upper FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_bb_width FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_atr_14 FLOAT64,
ADD COLUMN IF NOT EXISTS corn_etf_momentum_10 FLOAT64,

-- WEAT ETF (10 features)
ADD COLUMN IF NOT EXISTS weat_close FLOAT64,
ADD COLUMN IF NOT EXISTS weat_ma_7d FLOAT64,
ADD COLUMN IF NOT EXISTS weat_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS weat_ma_200d FLOAT64,
ADD COLUMN IF NOT EXISTS weat_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS weat_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS weat_bb_upper FLOAT64,
ADD COLUMN IF NOT EXISTS weat_bb_width FLOAT64,
ADD COLUMN IF NOT EXISTS weat_atr_14 FLOAT64,
ADD COLUMN IF NOT EXISTS weat_momentum_10 FLOAT64,

-- TIER 2: Ag stock fundamentals (5 stocks × 5 = 25 features)
-- ADM
ADD COLUMN IF NOT EXISTS adm_close FLOAT64,
ADD COLUMN IF NOT EXISTS adm_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS adm_beta FLOAT64,
ADD COLUMN IF NOT EXISTS adm_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS adm_market_cap FLOAT64,

-- BG
ADD COLUMN IF NOT EXISTS bg_close FLOAT64,
ADD COLUMN IF NOT EXISTS bg_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS bg_beta FLOAT64,
ADD COLUMN IF NOT EXISTS bg_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS bg_market_cap FLOAT64,

-- NTR
ADD COLUMN IF NOT EXISTS ntr_close FLOAT64,
ADD COLUMN IF NOT EXISTS ntr_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS ntr_beta FLOAT64,
ADD COLUMN IF NOT EXISTS ntr_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS ntr_market_cap FLOAT64,

-- DAR
ADD COLUMN IF NOT EXISTS dar_close FLOAT64,
ADD COLUMN IF NOT EXISTS dar_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS dar_beta FLOAT64,
ADD COLUMN IF NOT EXISTS dar_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS dar_market_cap FLOAT64,

-- TSN
ADD COLUMN IF NOT EXISTS tsn_close FLOAT64,
ADD COLUMN IF NOT EXISTS tsn_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS tsn_beta FLOAT64,
ADD COLUMN IF NOT EXISTS tsn_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS tsn_market_cap FLOAT64,

-- TIER 3: Energy & industrial (5 symbols × 5 = 25 features)
-- Brent Crude
ADD COLUMN IF NOT EXISTS brent_close FLOAT64,
ADD COLUMN IF NOT EXISTS brent_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS brent_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS brent_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS brent_ma_200d FLOAT64,

-- Copper
ADD COLUMN IF NOT EXISTS copper_close FLOAT64,
ADD COLUMN IF NOT EXISTS copper_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS copper_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS copper_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS copper_ma_200d FLOAT64,

-- Natural Gas (additional technicals beyond what we have)
ADD COLUMN IF NOT EXISTS natgas_yahoo_close FLOAT64,
ADD COLUMN IF NOT EXISTS natgas_yahoo_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS natgas_yahoo_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS natgas_yahoo_momentum_10 FLOAT64,
ADD COLUMN IF NOT EXISTS natgas_yahoo_roc_10 FLOAT64,

-- CF Industries
ADD COLUMN IF NOT EXISTS cf_close FLOAT64,
ADD COLUMN IF NOT EXISTS cf_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS cf_beta FLOAT64,
ADD COLUMN IF NOT EXISTS cf_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS cf_market_cap FLOAT64,

-- Mosaic
ADD COLUMN IF NOT EXISTS mos_close FLOAT64,
ADD COLUMN IF NOT EXISTS mos_pe_ratio FLOAT64,
ADD COLUMN IF NOT EXISTS mos_beta FLOAT64,
ADD COLUMN IF NOT EXISTS mos_analyst_target FLOAT64,
ADD COLUMN IF NOT EXISTS mos_market_cap FLOAT64,

-- TIER 4: Dollar drivers (4 FX × 5 = 20 features)
-- DXY Dollar Index
ADD COLUMN IF NOT EXISTS dxy_yahoo_close FLOAT64,
ADD COLUMN IF NOT EXISTS dxy_yahoo_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS dxy_yahoo_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS dxy_yahoo_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS dxy_yahoo_ma_200d FLOAT64,

-- BRL/USD
ADD COLUMN IF NOT EXISTS brlusd_close FLOAT64,
ADD COLUMN IF NOT EXISTS brlusd_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS brlusd_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS brlusd_momentum_10 FLOAT64,
ADD COLUMN IF NOT EXISTS brlusd_roc_10 FLOAT64,

-- CNY/USD
ADD COLUMN IF NOT EXISTS cnyusd_close FLOAT64,
ADD COLUMN IF NOT EXISTS cnyusd_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS cnyusd_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS cnyusd_momentum_10 FLOAT64,
ADD COLUMN IF NOT EXISTS cnyusd_roc_10 FLOAT64,

-- MXN/USD
ADD COLUMN IF NOT EXISTS mxnusd_close FLOAT64,
ADD COLUMN IF NOT EXISTS mxnusd_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS mxnusd_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS mxnusd_momentum_10 FLOAT64,
ADD COLUMN IF NOT EXISTS mxnusd_roc_10 FLOAT64,

-- BONUS: VIX & Credit (2 × 5 = 10 features)
-- VIX (Yahoo version for comparison with existing vix_level)
ADD COLUMN IF NOT EXISTS vix_yahoo_close FLOAT64,
ADD COLUMN IF NOT EXISTS vix_yahoo_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS vix_yahoo_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS vix_yahoo_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS vix_yahoo_bb_upper FLOAT64,

-- HYG (High Yield Credit)
ADD COLUMN IF NOT EXISTS hyg_close FLOAT64,
ADD COLUMN IF NOT EXISTS hyg_rsi_14 FLOAT64,
ADD COLUMN IF NOT EXISTS hyg_ma_30d FLOAT64,
ADD COLUMN IF NOT EXISTS hyg_macd_line FLOAT64,
ADD COLUMN IF NOT EXISTS hyg_bb_width FLOAT64;

-- Verify schema expansion
SELECT 
  COUNT(*) as total_columns,
  COUNT(*) - 334 as new_columns_added
FROM `cbi-v14.models_v4.INFORMATION_SCHEMA.COLUMNS`
WHERE table_name = 'zl_training_prod_allhistory_1m';







