-- ⚠️ CRITICAL: NO FAKE DATA ⚠️
-- This project uses ONLY real, verified data sources. NO placeholders, NO synthetic data, NO fake values.
-- All data must come from authenticated APIs, official sources, or validated historical records.
--

-- Vegas Intel - COMPLETE Cuisine Classification for ALL 142 Restaurants
-- READ ONLY from Glide data
-- Created: November 5, 2025
-- Maps every restaurant to cuisine type and oil consumption multiplier

CREATE OR REPLACE TABLE `cbi-v14.forecasting_data_warehouse.vegas_cuisine_multipliers` AS
SELECT
  glide_rowID,
  restaurant_name,
  cuisine_type,
  oil_multiplier,
  CURRENT_TIMESTAMP() as created_at,
  'Complete classification of all 142 open restaurants' as classification_source
FROM UNNEST([
  STRUCT('RKV1rvkwTnWTiEqPWa2lLQ' as glide_rowID, '1033 - America' as restaurant_name, 'American Diner' as cuisine_type, 1.5 as oil_multiplier),
  STRUCT('UWZU0K2qQ9utdmD8qnel9Q', '183 - EDR (Employee Dining Room)', 'Employee Dining', 1.4),
  STRUCT('7WNL0LxbReq02l9hQpDDhQ', "427 - Gallagher's Steakhouse", 'Steakhouse', 1.2),
  STRUCT('eZIiK712SBKnoaDm-e8yCw', '616 - Broadway Burger Bar', 'Burgers', 1.6),
  STRUCT('84If4yRYS7Gu0IWVctUMZQ', '622 - Production Kitchen', 'Production Kitchen', 1.5),
  STRUCT('a.7GT5ysaSVGjvlXeCrJ4UA', '643 - Village Streets (Fish & Chips)', 'Fish & Chips', 1.7),
  STRUCT('2CEpkOUZTtKq00lk3DlzIg', '90 Bar & Grill', 'American Grill', 1.5),
  STRUCT('60xFkFzaTS-igsoK49s5RA', 'Alder & Birch Steakhouse', 'Steakhouse', 1.2),
  STRUCT('D7U0.3WvSkK3YCZMA0FkDw', 'Amalfi', 'Italian', 1.5),
  STRUCT('MaxxO.lkRLmrUYTNse8jCQ', 'Angry Butcher', 'American Grill', 1.6),
  STRUCT('tharwIzyTAmvx0XzaM9G0Q', 'Bacchanal Buffet', 'Buffet', 2.2),
  STRUCT('Ur1hrkipTVqqXULerTPFrQ', 'Bailiwick', 'American Casual', 1.5),
  STRUCT('4z.trb7mRa-okwkjJYJJog', 'Banquets', 'Banquet', 1.5),
  STRUCT('Cnqm1-BHSreyWhLTKa7.VA', 'Banquets', 'Banquet', 1.5),
  STRUCT('E9y4W3sbT.ytlzx0NZCj8A', 'Banquets', 'Banquet', 1.5),
  STRUCT('tquE-rX0TSWpuW9ywcdUpQ', 'Banquets', 'Banquet', 1.5),
  STRUCT('qoFASqVSTUSIsWuwk3VA.Q', 'Banquets', 'Banquet', 1.5),
  STRUCT('uOKsik39QkWdUtNmonw.rw', 'Banquets', 'Banquet', 1.5),
  STRUCT('45JwsR1uR7GvHtYuWcCR-Q', 'Banquets - Ballroom (Hot Kitchen)', 'Banquet', 1.5),
  STRUCT('DjQopd2NSlC01i5QNNnO9Q', 'Banquets - Octavius', 'Banquet', 1.5),
  STRUCT('wExThRDwSLms6qMj5nUHVA', 'Banquets - Promenade', 'Banquet', 1.5),
  STRUCT('kQkDulZYT-qbOl7wtHSgGA', 'Bazaar Mar', 'Spanish Seafood', 1.7),
  STRUCT('2Y5xwOjmSSi6oYN60kbAiQ', 'Beijing Noodle', 'Chinese', 1.4),
  STRUCT('NMPDOVtATym07E1Ukg4S-g', 'Bistro 57', 'French Bistro', 1.3),
  STRUCT('uqlAE6NnS5aoOoQ47UNk-A', "Bobby's Burger", 'Burgers', 1.6),
  STRUCT('dvuzA0vZRTeAMn98UiiWSQ', "Bobby's Burger", 'Burgers', 1.6),
  STRUCT('QHaVDDa.QZCbxX.blWZVVw', 'Bowling Snack Bar', 'Snack Bar', 1.6),
  STRUCT('mqp3TtJ7SdKf9KI2rg7LNg', 'Bowling Snack Bar', 'Snack Bar', 1.6),
  STRUCT('sTyB4S0PRWi15--haabjTA', 'Bowling Snack Bar', 'Snack Bar', 1.6),
  STRUCT('dvfi0.fZQhGHUREsxaF-Hg', 'Bowling Snack Bar', 'Snack Bar', 1.6),
  STRUCT('o--dkGD8RvyQYIUANSLAhQ', 'Brasserie B', 'French Brasserie', 1.3),
  STRUCT('zPl9jON1SRCMX9GN4fNVsQ', 'Brew Pub', 'Pub', 1.7),
  STRUCT('IbWtI316TmSS3hTdKoChWA', 'Buffet', 'Buffet', 2.2),
  STRUCT('h4M-O3QfTg2HuWIDQszcWA', 'Buffet', 'Buffet', 2.2),
  STRUCT('WGLJU8SMSCO4PLzPyMhPdg', "Bugsy's Steakhouse", 'Steakhouse', 1.2),
  STRUCT('xVn86KaiSDuqHAm7zjb.7g', 'Cafe Americana', 'Cafe', 1.2),
  STRUCT('a-pQgyoGVST6rE..cJ9IU7g', 'Cafe Americano', 'Cafe', 1.2),
  STRUCT('GE4PwbvUT8alJDGLRZVg6g', 'California Noodle House', 'Chinese', 1.4),
  STRUCT('iMNetuKYSYuoPP6nrj8IKw', 'Canteen Food Hall - AttaBoy Burger', 'Burgers', 1.6),
  STRUCT('nAIR1prJQCa3zs6PTf9hjA', 'Canteen Food Hall - Southland Burrito', 'Mexican', 1.3),
  STRUCT('1aGx7sXOR4WSVZxdYKPhtg', 'Canteen Food Hall - Tender Crush', 'Burgers', 1.6),
  STRUCT('DMvgG2K4QbWuCqXUFJg-eg', 'Caramello', 'Bakery', 0.6),
  STRUCT('oV60nX08TnGyKb-d.4D88g', 'Carve Prime Rib Steakhouse', 'Steakhouse', 1.2),
  STRUCT('IrisAO0mSleLoOmq2QRpHw', 'Charleys Cheesesteak - Friday Dump', 'Cheesesteak', 1.4),
  STRUCT('ZB8hiP8yTLuQJN0kzKt2fQ', 'Charleys Cheesesteak - Monday Filter', 'Cheesesteak', 1.4),
  STRUCT('Eh-JdJ95QpuGFeGLL9SebA', 'Club House - Downstairs', 'Club House', 1.4),
  STRUCT('5xniX5paSc2ALrB9zYhcMQ', 'Club House - Upstairs', 'Club House', 1.4),
  STRUCT('N5yJKjJQRWijRardgrIMow', 'Copper Whisk Cafe', 'Cafe', 1.2),
  STRUCT('uQACOebASnCR1eMvsaOM1g', 'Cornerstone Steakhouse', 'Steakhouse', 1.2),
  STRUCT('zc2a.7aTQ0iP89HTeMU3uQ', 'Craft Kitchen', 'American Casual', 1.5),
  STRUCT('6EghLIujRFaggktj62Nkiw', 'DTG Pool', 'Pool/Club', 1.8),
  STRUCT('hSDwyWJvSk2AeBq8bPPbOg', "Darla's Southern Cajun Bistro", 'Cajun', 1.9),
  STRUCT('6OWpVUUtQme9YdK9y1JCyA', 'DiscoShow/Diner Ross - Independent', 'American Diner', 1.5),
  STRUCT('qRhhSgGtRY6dwpe7-dyS-w', 'Dominique Ansel', 'Bakery', 0.6),
  STRUCT('Z4BoS8z8SPKl-9B2lZrRIA', 'E.D.R. (Employee Dining Room)', 'Employee Dining', 1.4),
  STRUCT('zGvg9hidS0Kk6VQIhdZvQA', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('IJAnAJnpRhSfZZV553Y6Bw', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('WvllcanESNaX-nvnmc2tUw', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('WBGxpcKpRWWyOmt2s6z8DQ', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('I2laUIekSw6jLyS9OOqmDQ', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('hpQUfaTZSYa2zIaYE-8dVA', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('a-T8ikOZPQ4mAUxR6c5w67Q', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('fb8AMJSLR16S64M3kUZcoQ', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('UYM2aSAMRX6nGChBxUrQog', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('Jv88DkiUQ-KSUYv6D07Y.w', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('ZkhEGuIPRlirprDP60Kf4A', 'EDR - Employee Dining Room', 'Employee Dining', 1.4),
  STRUCT('Fj-gTbClSl2f0tjj6Z.9sw', 'EDR / Main Kitchen / Room Service', 'Employee Dining', 1.4),
  STRUCT('MJzD3UQoQraHrqEjASSmPA', 'EDR / Room Service', 'Employee Dining', 1.4),
  STRUCT('IpfhzzqlRR6GkPuoAisyYA', 'EDR / Room Service (Midday Filter)', 'Employee Dining', 1.4),
  STRUCT('RimL3pisTJaYtZmB1RI2KQ', 'EDR Daytime', 'Employee Dining', 1.4),
  STRUCT('a-0ABMftWQRKnAyVQBqSUag', 'El Burro Borracho', 'Mexican', 1.3),
  STRUCT('28egbGkETzmcAF87MHeQxg', 'Farm Cafe', 'Cafe', 1.2),
  STRUCT('K03kfP2yQQWpiejJhHBDNg', 'Favorite Bistro - Independent', 'Bistro', 1.3),
  STRUCT('61pDNJ5PSJSV5vnpOIKjaw', "Flanker's @Carver Road Hospitality", 'American Casual', 1.5),
  STRUCT('ZxcH5THXTrqx2Ra8CbSSyg', 'Flavortown - Guy Fieri', 'American Comfort', 1.8),
  STRUCT('5FuhwQrYQ3mH2BBFP.y13w', "Forum Food Court - Bobby's Burgers", 'Burgers', 1.6),
  STRUCT('99XaHBjJRqiCgB8yhddfzQ', 'Forum Food Court - Chicken Guy (Guy Fieri)', 'Fried Chicken', 2.0),
  STRUCT('Q9x7DzGXRla0hNNsJw23FQ', 'Forum Food Court - Mok Bar', 'Asian Fusion', 1.4),
  STRUCT('iaL.HbgPQGeASBKcRGA5CQ', 'Forum Food Court - Tortazo', 'Mexican', 1.3),
  STRUCT('op9bnKRhSrKPxXN4Bf9V4w', 'Fremont Pizza Company', 'Pizza', 1.1),
  STRUCT('bWjGLAfMQB-A6-.eAw0SDw', 'Fulton Street Food Hall - Noodles', 'Chinese', 1.4),
  STRUCT('ZJBNWv3KS4WJ20zVZfdLzw', 'Giada', 'Italian', 1.5),
  STRUCT('6yEa.z2jRh2OaO957Ka76Q', 'Giada - Pastry', 'Bakery', 0.6),
  STRUCT('iGmJdjTqQWC8aIgav0UjEw', 'Golf House', 'Club House', 1.4),
  STRUCT('EO.DEAWlSDWC8oVqzcOxow', 'Gonzalez y Gonzalez', 'Mexican', 1.3),
  STRUCT('xhU6Wx08SAK.2nDNVRxC3w', 'Gordon Ramsay Burgr', 'Burgers', 1.6),
  STRUCT('oykkZugBR0WGz5tc5jzrUw', 'Gordon Ramsay Burgr', 'Burgers', 1.6),
  STRUCT('3Y30.pB1RoiGTv0qv9S0-g', 'Gordon Ramsay Pub', 'Pub', 1.7),
  STRUCT('3W-dQydXQJGqb-FzikKn3g', 'Gordon Ramsay Steakhouse', 'Steakhouse', 1.2),
  STRUCT('oYxV-BKtSe-8WXLa40kraA', 'Guy Fieri', 'American Comfort', 1.8),
  STRUCT('3O3PCTODTRqY3XMRtCxOTQ', 'Hash House A Go-Go', 'American Comfort', 1.7),
  STRUCT('V9pzGgUvTEKKBH7vTNwY9g', 'Havana 1957 (Independent)', 'Cuban', 1.5),
  STRUCT('a-GRYdtkGQIeGwN3I-JjxKQ', "Hell's Kitchen", 'Contemporary American', 1.5),
  STRUCT('0groYogRSNK8n76gXYZa4Q', 'House of Blues (HOB)', 'American Casual', 1.5),
  STRUCT('9gHCie25QT2uDbDMX2ZpWg', "Huey Magoo's", 'Fried Chicken', 2.0),
  STRUCT('DGkVP94BRSefsWMPbxG6Qg', 'In-Room Dining (I.R.D.) / Pool', 'Pool/Club', 1.8),
  STRUCT('3GfUj.yiTYWyqr5HQjFYxA', "Jack Binion's Steakhouse", 'Steakhouse', 1.2),
  STRUCT('WpjN6.xxTYKPBzijSCsAnA', "Jason Aldean's Kitchen + Bar", 'American Casual', 1.5),
  STRUCT('uHsj7l.eQ9iIueptHSmhPA', "Jerry's", 'American Diner', 1.5),
  STRUCT('Mtao6iV4RaqLNcuvB9GVRQ', 'Lanai Express', 'Asian Fusion', 1.4),
  STRUCT('5ugENujURwuqlknEkUllPQ', 'Luckley Tavern', 'American Tavern', 1.5),
  STRUCT('pWAm18B7ShOR.7DoJ3Jcqg', 'MRKT', 'Asian Fusion', 1.4),
  STRUCT('EY6hLdsBTQScmpVJVlcFlA', 'Main Kitchen', 'Production Kitchen', 1.5),
  STRUCT('5vjgVPs6ScqidIwc66.8Lg', 'Main Kitchen', 'Production Kitchen', 1.5),
  STRUCT('GX8S-lCoQvOP8liY7YueoQ', 'Main Kitchen', 'Production Kitchen', 1.5),
  STRUCT('3X2bh6TuSJ6uPQsAfCD8Nw', 'Main Kitchen', 'Production Kitchen', 1.5),
  STRUCT('iE-4DigQR--d-kjU78WwKg', "Main Kitchen (GR Burgr & Pinky's)", 'Production Kitchen', 1.5),
  STRUCT('J8dxKi2rTlOzQTGwspFXwQ', 'Main Kitchen - Zone 3', 'Production Kitchen', 1.5),
  STRUCT('Asxu2ufuRN6lVG759qJ-ZQ', 'Market Street Cafe', 'Cafe', 1.2),
  STRUCT('S.cnioZQQAaXLj3rd8igFw', 'Martha Stewart - Bedford', 'American Upscale', 1.3),
  STRUCT('q9wiX2..TYSxjQT86eblgQ', 'Mermaid - Zone 4', 'Asian', 1.4),
  STRUCT('Gg0o8PMWSMmlE0uFIwLJdw', 'Mi Casa - Zone 2', 'Mexican', 1.3),
  STRUCT('z4mrsm-GQ-O2s7rvi89GPA', 'Nobu', 'Sushi', 0.3),
  STRUCT('pxunTEBIQ-6Qb0EE7kNfQQ', 'Ondori Asian Kitchen', 'Japanese Yakitori', 1.4),
  STRUCT('QOa8HFikTlCEyAf6vsEp5w', 'Orleans Arena', 'Arena Concessions', 1.6),
  STRUCT('C7KTgyGhQxKwPJTACHx9Qw', "Pinky's", 'American Casual', 1.5),
  STRUCT('EIUAO2uLRJmq6RFSOpGFGg', 'Pool', 'Pool/Club', 1.8),
  STRUCT('a-h0.uBRdQy-epNnQE.bwMg', 'Pool (Back EDR)', 'Pool/Club', 1.8),
  STRUCT('0qjFKidrRwCGcCIiBS4cWg', 'Pool Beach Club', 'Pool/Club', 1.8),
  STRUCT('vquBfXjjS6isYkq78ITkJw', 'Redwood Steakhouse', 'Steakhouse', 1.2),
  STRUCT('h9pUX9gCTTet06DILF2M9g', 'Room Service', 'Hotel Dining', 1.3),
  STRUCT('ZVqBhCCIQ52FaFUzZRuOVQ', 'Salted Lime', 'Mexican', 1.3),
  STRUCT('vtwC7JliQWq6.UTh3ljzwA', 'Service Kitchen 1', 'Production Kitchen', 1.5),
  STRUCT('aXQq-eAuQGKVFlr-mtpYvg', 'Service Kitchen 2', 'Production Kitchen', 1.5),
  STRUCT('YO4618.ZQeq-Hjopco6Lsw', "Smokey Joe's", 'Barbecue', 1.7),
  STRUCT('L.vL0WWvTSKwXk2uUDQAEQ', 'Sports Deli', 'Deli', 1.3),
  STRUCT('a.s1AkqtzRnS-2TGjSBVplQ', 'Sports Deli', 'Deli', 1.3),
  STRUCT('41nsRcHDSpqzjxE6quVlHg', 'Stanton Social Club', 'American Upscale', 1.5),
  STRUCT('omfgzx26QIKN1JOK7BCcEg', 'Su Casa - Zone 2', 'Mexican', 1.3),
  STRUCT('8jWcyO7YSwCtCE6UXE0b6g', 'Sundance Cafe - Zone 5', 'Cafe', 1.2),
  STRUCT('iqn1oXDRR0-e4LK1jEG.CA', 'Superfrico', 'Italian', 1.5),
  STRUCT('a-Io2MZWwTz6YkDmtgTrpMg', 'TDR (Team Dining Room) - Zone 2', 'Employee Dining', 1.4),
  STRUCT('2f.mG1qdTtujSwPDvGvR9Q', 'Tomo Noodles', 'Chinese', 1.4),
  STRUCT('7utwLMbfS46OFDH70IEp7w', "Tony Roma's", 'Barbecue', 1.7),
  STRUCT('hJ4SwrLSRnOIwrOwnVh6WQ', 'Triple George Grill', 'American Grill', 1.5),
  STRUCT('EJi-DM8wQpimIx5cx7g0yA', 'Twin Creeks - Zone 2', 'American Casual', 1.4),
  STRUCT('XK0xmnCSStC38oGmjs2W0Q', 'Vanderpump', 'American Upscale', 1.3),
  STRUCT('XJGKQnxtTBSJcRkpF0hXWQ', "Victory's Cafe", 'Cafe', 1.2),
  STRUCT('5aRV3bYVShapr.clw0FM3g', 'Voodoo Steakhouse', 'Steakhouse', 1.2),
  STRUCT('dUf8xK2MTeufXqS2OpAvqQ', "William B's Steakhouse", 'Steakhouse', 1.2),
  STRUCT('t9XxGoZhSSSuooi.ZZwOeQ', 'Wuhu Noodle - Zone 1', 'Chinese', 1.4),
  STRUCT('44nmN6hESde5VON1s81rAA', 'Yolo - Independant', 'American Casual', 1.5)
]);

-- Table metadata
-- COMMENT ON TABLE `cbi-v14.forecasting_data_warehouse.vegas_cuisine_multipliers` IS 
-- 'Cuisine-based oil consumption multipliers for Vegas restaurants. Maps each restaurant to cuisine type for accurate forecasting. READ ONLY from Glide data.';
